apiVersion: v1
kind: Service
metadata:
  name: pathiel-data-api
  namespace: pathiel
  labels:
    app.kubernetes.io/name: pathiel-data-api
    app.kubernetes.io/part-of: pathiel-data-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pathiel-data-api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
