#!/usr/bin/env python3
"""Compile the utility CSS the templates actually use into static/app.css.

Replaces the in-browser Tailwind JIT runtime (static/tailwind.js — a dev
tool: ~300KB of JS, flash-of-unstyled on every load) with a static
stylesheet, Tailwind-v4 style: tokens compiled ahead of time, zero runtime.

Deterministic by design: a fixed utility→declaration map plus two arbitrary-
value families (max-w-[..], text-[..]) and two variants (md:, last:). The
script scans every template for class tokens and HARD-FAILS on any token
that looks like a utility but has no mapping — so a template edit that
invents a new class breaks the build loudly instead of rendering unstyled.
The gate test (test_dashboard_pages.py) imports these functions and asserts
the committed app.css is exactly what this script emits.

Usage: python scripts/build_static_css.py [--check]
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEMPLATES = ROOT / "pathiel" / "templates"
OUT = ROOT / "pathiel" / "static" / "app.css"

# Minimal preflight — the subset of Tailwind's reset these pages rely on.
PREFLIGHT = """\
/* generated by scripts/build_static_css.py — do not edit by hand */
*,::before,::after{box-sizing:border-box;border-width:0;border-style:solid;border-color:currentColor}
html{line-height:1.5;-webkit-text-size-adjust:100%;tab-size:4}
body{margin:0;line-height:inherit}
p,h1,h2,h3,h4,h5,h6{margin:0}
button,input,select,textarea{font:inherit;color:inherit;margin:0;padding:0}
button{background:transparent;cursor:pointer;text-transform:none;-webkit-appearance:button}
table{border-collapse:collapse;border-color:inherit;text-indent:0}
a{color:inherit;text-decoration:inherit}
canvas,svg{display:block}
"""

# Exact utility → declarations (Tailwind default scale, only what we use).
UTILS: dict[str, str] = {
    "flex": "display:flex", "grid": "display:grid", "hidden": "display:none",
    "relative": "position:relative", "absolute": "position:absolute",
    "inset-0": "inset:0", "min-h-screen": "min-height:100vh",
    "w-full": "width:100%", "mx-auto": "margin-left:auto;margin-right:auto",
    "ml-auto": "margin-left:auto", "overflow-x-auto": "overflow-x:auto",
    "grid-cols-1": "grid-template-columns:repeat(1,minmax(0,1fr))",
    "grid-cols-2": "grid-template-columns:repeat(2,minmax(0,1fr))",
    "grid-cols-4": "grid-template-columns:repeat(4,minmax(0,1fr))",
    "grid-cols-5": "grid-template-columns:repeat(5,minmax(0,1fr))",
    "items-center": "align-items:center", "items-baseline": "align-items:baseline",
    "justify-between": "justify-content:space-between",
    "justify-center": "justify-content:center", "flex-wrap": "flex-wrap:wrap",
    "p-0": "padding:0", "p-4": "padding:1rem", "p-5": "padding:1.25rem",
    "px-6": "padding-left:1.5rem;padding-right:1.5rem",
    "py-2": "padding-top:.5rem;padding-bottom:.5rem",
    "py-2.5": "padding-top:.625rem;padding-bottom:.625rem",
    "py-3": "padding-top:.75rem;padding-bottom:.75rem",
    "py-6": "padding-top:1.5rem;padding-bottom:1.5rem",
    "pr-3": "padding-right:.75rem",
    "mb-1": "margin-bottom:.25rem", "mb-2": "margin-bottom:.5rem",
    "mb-3": "margin-bottom:.75rem", "mb-4": "margin-bottom:1rem",
    "mb-5": "margin-bottom:1.25rem", "mb-6": "margin-bottom:1.5rem",
    "mt-1": "margin-top:.25rem", "mt-2": "margin-top:.5rem",
    "mt-3": "margin-top:.75rem", "mt-6": "margin-top:1.5rem",
    "mt-8": "margin-top:2rem",
    "gap-1": "gap:.25rem", "gap-2": "gap:.5rem", "gap-3": "gap:.75rem",
    "gap-4": "gap:1rem", "gap-6": "gap:1.5rem",
    "text-xs": "font-size:.75rem;line-height:1rem",
    "text-center": "text-align:center", "text-left": "text-align:left",
    "text-right": "text-align:right", "font-semibold": "font-weight:600",
    "uppercase": "text-transform:uppercase", "tracking-wider": "letter-spacing:.05em",
    "leading-relaxed": "line-height:1.625", "underline": "text-decoration-line:underline",
    "whitespace-nowrap": "white-space:nowrap", "cursor-pointer": "cursor:pointer",
    "bg-transparent": "background-color:transparent",
    "border-0": "border-width:0", "border-b": "border-bottom-width:1px",
    "align-middle": "vertical-align:middle",
}
ARBITRARY = {  # family prefix -> css property
    "max-w": "max-width",
    "text": "font-size",
}
MD_BREAKPOINT = "48rem"

# A token in a template that matches one of these families MUST resolve to a
# rule, or the build fails — this is the guard against silent unstyling.
UTILITY_SHAPE = re.compile(
    r"^(md:|last:)?("
    r"(p|px|py|pr|pl|pt|pb|m|mx|my|mb|mt|ml|mr|gap|max-w|min-h|w|h|text|font|"
    r"tracking|leading|grid-cols|inset|border|bg|items|justify|whitespace|"
    r"align|overflow-x)(-|\[)"
    r"|flex$|grid$|hidden$|relative$|absolute$|uppercase$|underline$|"
    r"cursor-pointer$|flex-wrap$|mx-auto$|ml-auto$|min-h-screen$|w-full$"
    r")"
)


def esc_cls(tok: str) -> str:
    return re.sub(r"([\[\].:%])", r"\\\1", tok)


def scan_tokens() -> set[str]:
    toks: set[str] = set()
    for f in sorted(TEMPLATES.glob("*.html")):
        for m in re.findall(r'class="([^"]+)"', f.read_text()):
            for t in m.split():
                if "$" not in t and "'" not in t and t not in ("+", ":", "?", "===", ">=", "0"):
                    toks.add(t)
    return toks


def rule_for(tok: str) -> str | None:
    """CSS rule for one token, or None if it's not a utility we own."""
    variant, base = "", tok
    if tok.startswith("md:"):
        variant, base = "md", tok[3:]
    elif tok.startswith("last:"):
        variant, base = "last", tok[5:]

    decl = UTILS.get(base)
    if decl is None:
        m = re.match(r"^([a-z-]+)-\[(.+)\]$", base)
        if m and m.group(1) in ARBITRARY:
            decl = f"{ARBITRARY[m.group(1)]}:{m.group(2)}"
    if decl is None:
        return None

    sel = f".{esc_cls(tok)}"
    if variant == "last":
        return f"{sel}:last-child{{{decl}}}"
    if variant == "md":
        return f"@media (min-width:{MD_BREAKPOINT}){{{sel}{{{decl}}}}}"
    return f"{sel}{{{decl}}}"


def build() -> str:
    toks = scan_tokens()
    rules, unknown = [], []
    for tok in sorted(toks):
        r = rule_for(tok)
        if r is not None:
            rules.append(r)
        elif UTILITY_SHAPE.match(tok):
            unknown.append(tok)
    if unknown:
        raise SystemExit(f"unmapped utility classes (add to UTILS): {unknown}")
    return PREFLIGHT + "\n".join(rules) + "\n"


if __name__ == "__main__":
    css = build()
    if "--check" in sys.argv:
        if OUT.read_text() != css:
            raise SystemExit("static/app.css is stale — run scripts/build_static_css.py")
        print("app.css up to date")
    else:
        OUT.write_text(css)
        print(f"wrote {OUT} ({len(css)} bytes, {css.count(chr(10))} lines)")
